package org.autojs.plugin.r8compiler.api

import org.autojs.plugin.protocol.wire.TaggedWireDocument
import org.autojs.plugin.protocol.wire.TaggedWireLimits
import org.autojs.plugin.protocol.wire.TaggedWireWriter
import java.nio.ByteBuffer
import java.nio.ByteOrder

object R8CompilerCodec {
    private val limits = TaggedWireLimits(R8CompilerContract.MAX_METADATA_BYTES, R8CompilerContract.MAX_METADATA_BYTES, 1_024)

    fun encodeInfo(v: R8CompilerInfo): ByteArray { R8CompilerValidation.validateInfo(v); return writer(R8CompilerContract.SCHEMA_COMPILER_INFO).int32(1,v.protocolMin.major,true).int32(2,v.protocolMin.minor,true).int32(3,v.protocolMax.major,true).int32(4,v.protocolMax.minor,true).string(5,v.providerId,true).string(6,v.providerVersionName,true).int64(7,v.providerVersionCode,true).apply { v.minHostVersionCode?.let { int64(8,it) }; v.maxHostVersionCode?.let { int64(9,it) } }.encode() }
    fun decodeInfo(b: ByteArray): R8CompilerInfo = doc(b,R8CompilerContract.SCHEMA_COMPILER_INFO,(1..9).toSet()).let { d -> R8CompilerInfo(R8ProtocolVersion(d.requireInt32(1),d.requireInt32(2)),R8ProtocolVersion(d.requireInt32(3),d.requireInt32(4)),d.requireString(5),d.requireString(6),d.requireInt64(7),d.optionalInt64(8),d.optionalInt64(9)).also(R8CompilerValidation::validateInfo) }

    fun encodeCapabilities(v: R8CompilerCapabilities): ByteArray { R8CompilerValidation.validateCapabilities(v); return writer(R8CompilerContract.SCHEMA_CAPABILITIES).int32(1,v.compilerFamily.wireCode,true).string(2,v.compilerVersion,true).apply { v.profiles.forEach { int32(3,it.wireCode,true) } }.int32(4,v.minApi,true).int32(5,v.maxApi,true).int32(6,v.inputLayout.wireCode,true).int32(7,v.outputLayout.wireCode,true).apply { v.artifactRoles.forEach { int32(8,it.wireCode,true) } }.int32(9,v.determinismClaim.wireCode,true).int32(10,v.runtimeLibraryModel.wireCode,true).int32(11,v.rulePolicyVersion,true).int32(12,v.canonicalizationPolicyVersion,true).int32(13,v.implicitRulePolicy.wireCode,true).document(14,encodeLimits(v.limits),true).apply { v.runtimeLibraryIdentities.forEach { document(15,encodeRuntime(it),true) } }.bytes(16,v.runtimeLibraryFingerprint.toByteArray(),true).bytes(17,v.capabilityFingerprint.toByteArray(),true).boolean(18,v.supportsMultiDex,true).encode() }
    fun decodeCapabilities(b: ByteArray): R8CompilerCapabilities { val d=doc(b,R8CompilerContract.SCHEMA_CAPABILITIES,(1..18).toSet(),setOf(3,8,15)); return R8CompilerCapabilities(enumCode(d.requireInt32(1)),d.requireString(2),repeatedInt32(b,3).map(::profile),d.requireInt32(4),d.requireInt32(5),enumCode(d.requireInt32(6)),enumCode(d.requireInt32(7)),repeatedInt32(b,8).map(::artifactRole),enumCode(d.requireInt32(9)),enumCode(d.requireInt32(10)),d.requireInt32(11),d.requireInt32(12),enumCode(d.requireInt32(13)),decodeLimits(d.requireDocument(14)),d.documents(15).map(::decodeRuntime),R8Sha256.fromBytes(d.requireBytes(16)),R8Sha256.fromBytes(d.requireBytes(17)),d.requireBoolean(18)).also(R8CompilerValidation::validateCapabilities) }

    fun encodeRequest(v:R8CompileRequest):ByteArray { R8CompilerValidation.validateRequest(v); return writer(R8CompilerContract.SCHEMA_COMPILE_REQUEST).bytes(1,v.requestId.toByteArray(),true).int32(2,v.protocolVersion.major,true).int32(3,v.protocolVersion.minor,true).int32(4,v.compilerFamily.wireCode,true).int32(5,v.compilerIntent.wireCode,true).int32(6,v.fallbackPolicy.wireCode,true).int32(7,v.profile.wireCode,true).int32(8,v.minApi,true).int32(9,v.inputLayout.wireCode,true).apply{v.inputIdentities.forEach{document(10,encodeInput(it),true)}}.bytes(11,v.inputSetFingerprint.toByteArray(),true).int64(12,v.inputBundleSizeBytes,true).bytes(13,v.inputBundleSha256.toByteArray(),true).int32(14,v.runtimeLibraryModel.wireCode,true).bytes(15,v.expectedRuntimeLibraryFingerprint.toByteArray(),true).bytes(16,v.expectedCapabilityFingerprint.toByteArray(),true).int32(17,v.canonicalizationPolicyVersion,true).int32(18,v.rulePolicyVersion,true).int32(19,v.outputLayout.wireCode,true).apply{v.requestedArtifacts.forEach{document(20,encodeRequested(it),true)}}.int64(21,v.maxOutputBundleBytes,true).int32(22,v.diagnosticByteLimit,true).int64(23,v.timeoutMillis,true).encode() }
    fun decodeRequest(b:ByteArray):R8CompileRequest { val d=doc(b,R8CompilerContract.SCHEMA_COMPILE_REQUEST,(1..23).toSet(),setOf(10,20)); return R8CompileRequest(R8RequestId.fromBytes(d.requireBytes(1)),R8ProtocolVersion(d.requireInt32(2),d.requireInt32(3)),enumCode(d.requireInt32(4)),enumCode(d.requireInt32(5)),enumCode(d.requireInt32(6)),profile(d.requireInt32(7)),d.requireInt32(8),enumCode(d.requireInt32(9)),d.documents(10).map(::decodeInput),R8Sha256.fromBytes(d.requireBytes(11)),d.requireInt64(12),R8Sha256.fromBytes(d.requireBytes(13)),enumCode(d.requireInt32(14)),R8Sha256.fromBytes(d.requireBytes(15)),R8Sha256.fromBytes(d.requireBytes(16)),d.requireInt32(17),d.requireInt32(18),enumCode(d.requireInt32(19)),d.documents(20).map(::decodeRequested),d.requireInt64(21),d.requireInt32(22),d.requireInt64(23)).also(R8CompilerValidation::validateRequest) }

    fun encodeRetraceMetadata(v:R8RetraceMetadata):ByteArray { R8CompilerValidation.validateRetraceMetadata(v); return writer(R8CompilerContract.SCHEMA_RETRACE_METADATA).bytes(1,v.mappingSha256.toByteArray(),true).string(2,v.formatId,true).string(3,v.formatVersion,true).string(4,v.compilerVersion,true).bytes(5,v.capabilityFingerprint.toByteArray(),true).bytes(6,v.runtimeLibraryFingerprint.toByteArray(),true).bytes(7,v.inputSetFingerprint.toByteArray(),true).int32(8,v.minApi,true).int32(9,v.profile.wireCode,true).encode() }
    fun decodeRetraceMetadata(b:ByteArray):R8RetraceMetadata { val d=doc(b,R8CompilerContract.SCHEMA_RETRACE_METADATA,(1..9).toSet()); return R8RetraceMetadata(R8Sha256.fromBytes(d.requireBytes(1)),d.requireString(2),d.requireString(3),d.requireString(4),R8Sha256.fromBytes(d.requireBytes(5)),R8Sha256.fromBytes(d.requireBytes(6)),R8Sha256.fromBytes(d.requireBytes(7)),d.requireInt32(8),profile(d.requireInt32(9))).also(R8CompilerValidation::validateRetraceMetadata) }

    fun encodeStarted(v:R8Started):ByteArray { R8CompilerValidation.validateStarted(v); return writer(R8CompilerContract.SCHEMA_STARTED).bytes(1,v.requestId.toByteArray(),true).int64(2,v.sequence,true).int32(3,v.protocolVersion.major,true).int32(4,v.protocolVersion.minor,true).int32(5,v.compilerFamily.wireCode,true).string(6,v.compilerVersion,true).bytes(7,v.capabilityFingerprint.toByteArray(),true).bytes(8,v.runtimeLibraryFingerprint.toByteArray(),true).int32(9,v.profile.wireCode,true).int64(10,v.queueElapsedMillis,true).encode() }
    fun decodeStarted(b:ByteArray):R8Started { val d=doc(b,R8CompilerContract.SCHEMA_STARTED,(1..10).toSet()); return R8Started(R8RequestId.fromBytes(d.requireBytes(1)),d.requireInt64(2),R8ProtocolVersion(d.requireInt32(3),d.requireInt32(4)),enumCode(d.requireInt32(5)),d.requireString(6),R8Sha256.fromBytes(d.requireBytes(7)),R8Sha256.fromBytes(d.requireBytes(8)),profile(d.requireInt32(9)),d.requireInt64(10)).also(R8CompilerValidation::validateStarted) }
    fun encodeProgress(v:R8Progress):ByteArray { R8CompilerValidation.validateProgress(v); return writer(R8CompilerContract.SCHEMA_PROGRESS).bytes(1,v.requestId.toByteArray(),true).int64(2,v.sequence,true).int32(3,v.stage.wireCode,true).apply{v.current?.let{int64(4,it)};v.total?.let{int64(5,it)}}.encode() }
    fun decodeProgress(b:ByteArray):R8Progress { val d=doc(b,R8CompilerContract.SCHEMA_PROGRESS,(1..5).toSet()); return R8Progress(R8RequestId.fromBytes(d.requireBytes(1)),d.requireInt64(2),enumCode(d.requireInt32(3)),d.optionalInt64(4),d.optionalInt64(5)).also(R8CompilerValidation::validateProgress) }

    fun encodeResult(v:R8Result):ByteArray { R8CompilerValidation.validateResult(v); return writer(R8CompilerContract.SCHEMA_RESULT).bytes(1,v.requestId.toByteArray(),true).int32(2,v.compilerFamily.wireCode,true).string(3,v.compilerVersion,true).bytes(4,v.capabilityFingerprint.toByteArray(),true).bytes(5,v.runtimeLibraryFingerprint.toByteArray(),true).bytes(6,v.inputSetFingerprint.toByteArray(),true).int32(7,v.profile.wireCode,true).int32(8,v.minApi,true).int32(9,v.outputLayout.wireCode,true).int64(10,v.outputBundleSizeBytes,true).bytes(11,v.outputBundleSha256.toByteArray(),true).apply{v.artifactIdentities.forEach{document(12,encodeArtifact(it),true)}}.int32(13,v.determinismClaim.wireCode,true).int64(14,v.elapsedMillis,true).apply{v.diagnostics.forEach{document(15,encodeDiagnostic(it),true)}}.encode() }
    fun decodeResult(b:ByteArray):R8Result { val d=doc(b,R8CompilerContract.SCHEMA_RESULT,(1..15).toSet(),setOf(12,15)); return R8Result(R8RequestId.fromBytes(d.requireBytes(1)),enumCode(d.requireInt32(2)),d.requireString(3),R8Sha256.fromBytes(d.requireBytes(4)),R8Sha256.fromBytes(d.requireBytes(5)),R8Sha256.fromBytes(d.requireBytes(6)),profile(d.requireInt32(7)),d.requireInt32(8),enumCode(d.requireInt32(9)),d.requireInt64(10),R8Sha256.fromBytes(d.requireBytes(11)),d.documents(12).map(::decodeArtifact),enumCode(d.requireInt32(13)),d.requireInt64(14),d.documents(15).map(::decodeDiagnostic)).also(R8CompilerValidation::validateResult) }
    fun encodeError(v:R8Error):ByteArray { R8CompilerValidation.validateError(v); return writer(R8CompilerContract.SCHEMA_ERROR).bytes(1,v.requestId.toByteArray(),true).int32(2,v.code.wireCode,true).int32(3,v.phase.wireCode,true).string(4,v.message,true).int64(5,v.elapsedMillis,true).apply{v.diagnostics.forEach{document(6,encodeDiagnostic(it),true)}}.encode() }
    fun decodeError(b:ByteArray):R8Error { val d=doc(b,R8CompilerContract.SCHEMA_ERROR,(1..6).toSet(),setOf(6)); return R8Error(R8RequestId.fromBytes(d.requireBytes(1)),enumCode(d.requireInt32(2)),enumCode(d.requireInt32(3)),d.requireString(4),d.requireInt64(5),d.documents(6).map(::decodeDiagnostic)).also(R8CompilerValidation::validateError) }
    fun encodeCancellation(v:R8Cancellation):ByteArray { R8CompilerValidation.validateCancellation(v); return writer(R8CompilerContract.SCHEMA_CANCELLATION).bytes(1,v.requestId.toByteArray(),true).int32(2,v.reason.wireCode,true).int32(3,v.phase.wireCode,true).int64(4,v.elapsedMillis,true).encode() }
    fun decodeCancellation(b:ByteArray):R8Cancellation { val d=doc(b,R8CompilerContract.SCHEMA_CANCELLATION,(1..4).toSet()); return R8Cancellation(R8RequestId.fromBytes(d.requireBytes(1)),enumCode(d.requireInt32(2)),enumCode(d.requireInt32(3)),d.requireInt64(4)).also(R8CompilerValidation::validateCancellation) }

    private fun encodeLimits(v:R8ResourceLimits):ByteArray { val w=writer(R8CompilerContract.SCHEMA_RESOURCE_LIMITS); w.int64(1,v.maxProgramBytes,true).int32(2,v.maxClasspathCount,true).int64(3,v.maxClasspathJarBytes,true).int64(4,v.maxTotalClasspathBytes,true).int32(5,v.maxKeepRuleFiles,true).int32(6,v.maxConsumerRuleFiles,true).int64(7,v.maxRuleFileBytes,true).int64(8,v.maxTotalRuleBytes,true).int32(9,v.maxRuleLinesPerFile,true).int32(10,v.maxTotalRuleLines,true).int32(11,v.maxRuleLineBytes,true).int64(12,v.maxInputBundleBytes,true).int32(13,v.maxArchiveEntries,true).int32(14,v.maxTotalArchiveEntries,true).int64(15,v.maxUncompressedProgramBytes,true).int64(16,v.maxTotalUncompressedInputBytes,true).int64(17,v.maxTotalClassBytes,true).int64(18,v.maxSingleClassBytes,true).int64(19,v.maxOutputBundleBytes,true).int64(20,v.maxDexZipBytes,true).int64(21,v.maxMappingBytes,true).int64(22,v.maxSeedsBytes,true).int64(23,v.maxUsageBytes,true).int64(24,v.maxRetraceMetadataBytes,true).int32(25,v.maxDexEntries,true).int32(26,v.maxDiagnosticBytes,true).int32(27,v.maxConcurrentSessions,true).int64(28,v.defaultTimeoutMillis,true).int64(29,v.maxTimeoutMillis,true);return w.encode() }
    private fun decodeLimits(b:ByteArray):R8ResourceLimits { val d=doc(b,R8CompilerContract.SCHEMA_RESOURCE_LIMITS,(1..29).toSet()); return R8ResourceLimits(d.requireInt64(1),d.requireInt32(2),d.requireInt64(3),d.requireInt64(4),d.requireInt32(5),d.requireInt32(6),d.requireInt64(7),d.requireInt64(8),d.requireInt32(9),d.requireInt32(10),d.requireInt32(11),d.requireInt64(12),d.requireInt32(13),d.requireInt32(14),d.requireInt64(15),d.requireInt64(16),d.requireInt64(17),d.requireInt64(18),d.requireInt64(19),d.requireInt64(20),d.requireInt64(21),d.requireInt64(22),d.requireInt64(23),d.requireInt64(24),d.requireInt32(25),d.requireInt32(26),d.requireInt32(27),d.requireInt64(28),d.requireInt64(29)) }
    private fun encodeRuntime(v:R8RuntimeLibraryIdentity)=writer(R8CompilerContract.SCHEMA_RUNTIME_LIBRARY_IDENTITY).int64(1,v.sizeBytes,true).bytes(2,v.contentSha256.toByteArray(),true).encode()
    private fun decodeRuntime(b:ByteArray)=doc(b,R8CompilerContract.SCHEMA_RUNTIME_LIBRARY_IDENTITY,setOf(1,2)).let{R8RuntimeLibraryIdentity(it.requireInt64(1),R8Sha256.fromBytes(it.requireBytes(2)))}
    private fun encodeInput(v:R8InputIdentity)=writer(R8CompilerContract.SCHEMA_INPUT_IDENTITY).int32(1,v.role.wireCode,true).int32(2,v.ordinal,true).int32(3,v.ownerClasspathOrdinal,true).int64(4,v.sizeBytes,true).bytes(5,v.contentSha256.toByteArray(),true).bytes(6,v.ownerClasspathSha256.toByteArray(),true).encode()
    private fun decodeInput(b:ByteArray)=doc(b,R8CompilerContract.SCHEMA_INPUT_IDENTITY,(1..6).toSet()).let{R8InputIdentity(enumCode(it.requireInt32(1)),it.requireInt32(2),it.requireInt32(3),it.requireInt64(4),R8Sha256.fromBytes(it.requireBytes(5)),R8Sha256.fromBytes(it.requireBytes(6)))}
    private fun encodeRequested(v:R8RequestedArtifact)=writer(R8CompilerContract.SCHEMA_REQUESTED_ARTIFACT).int32(1,v.role.wireCode,true).int64(2,v.maxBytes,true).encode()
    private fun decodeRequested(b:ByteArray)=doc(b,R8CompilerContract.SCHEMA_REQUESTED_ARTIFACT,setOf(1,2)).let{R8RequestedArtifact(artifactRole(it.requireInt32(1)),it.requireInt64(2))}
    private fun encodeArtifact(v:R8ArtifactIdentity)=writer(R8CompilerContract.SCHEMA_ARTIFACT_IDENTITY).int32(1,v.role.wireCode,true).int32(2,v.ordinal,true).int64(3,v.sizeBytes,true).bytes(4,v.contentSha256.toByteArray(),true).encode()
    private fun decodeArtifact(b:ByteArray)=doc(b,R8CompilerContract.SCHEMA_ARTIFACT_IDENTITY,(1..4).toSet()).let{R8ArtifactIdentity(artifactRole(it.requireInt32(1)),it.requireInt32(2),it.requireInt64(3),R8Sha256.fromBytes(it.requireBytes(4)))}
    private fun encodeDiagnostic(v:R8Diagnostic)=writer(R8CompilerContract.SCHEMA_DIAGNOSTIC).int32(1,v.severity.wireCode,true).string(2,v.code,true).string(3,v.message,true).encode()
    private fun decodeDiagnostic(b:ByteArray)=doc(b,R8CompilerContract.SCHEMA_DIAGNOSTIC,(1..3).toSet()).let{R8Diagnostic(enumCode(it.requireInt32(1)),it.requireString(2),it.requireString(3))}
    private fun writer(schema:Int)=TaggedWireWriter(schema,R8CompilerContract.SCHEMA_MAJOR,R8CompilerContract.SCHEMA_MINOR,limits)
    private fun doc(b:ByteArray,schema:Int,tags:Set<Int>,repeated:Set<Int> = emptySet())=TaggedWireDocument.decode(b,limits).requireSchema(schema,R8CompilerContract.SCHEMA_MAJOR).rejectUnknownRequiredFields(tags).validateKnownCardinality(tags,repeated)
    private inline fun <reified E> enumCode(code:Int):E where E:Enum<E>, E:R8WireCode = enumValues<E>().firstOrNull { it.wireCode == code } ?: throw R8ContractException(R8ContractViolation.UNKNOWN_ENUM,"Unknown enum code $code")
    private fun profile(v:Int)=R8CompilerProfile.values().firstOrNull{it.wireCode==v}?:throw R8ContractException(R8ContractViolation.UNKNOWN_ENUM,"Unknown profile $v")
    private fun artifactRole(v:Int)=R8ArtifactRole.values().firstOrNull{it.wireCode==v}?:throw R8ContractException(R8ContractViolation.UNKNOWN_ENUM,"Unknown artifact role $v")
    private fun repeatedInt32(bytes:ByteArray, wantedTag:Int):List<Int> {
        val buffer=ByteBuffer.wrap(bytes).order(ByteOrder.BIG_ENDIAN); buffer.position(24); val count=buffer.int
        val result=ArrayList<Int>()
        repeat(count){ val tag=buffer.int; val type=buffer.int; buffer.int; val length=buffer.int; if(tag==wantedTag){ if(type!=1||length!=4) throw R8ContractException(R8ContractViolation.INVALID_VALUE,"Repeated int field has invalid shape"); result+=buffer.int } else buffer.position(buffer.position()+length) }
        return result
    }
}
